apiVersion: v1
entries:
  csi-s3:
  - apiVersion: v1
    appVersion: 0.43.7
    created: "2026-09-28T04:09:39.847125783Z"
    description: Container Storage Interface (CSI) driver for S3 volumes
    digest: 7a32f9149960328d4f28050c4f49a0637d0d9a3ecfe6a54589d69a189cd83293
    home: https://github.com/yandex-cloud/k8s-csi-s3
    icon: https://raw.githubusercontent.com/yandex-cloud/geesefs/master/doc/geesefs.png
    keywords:
    - s3
    name: csi-s3
    sources:
    - https://github.com/yandex-cloud/k8s-csi-s3/deploy/helm
    urls:
    - https://warjiang.github.io/k8s-csi-s3/charts/csi-s3-0.43.7.tgz
    version: 0.43.7
generated: "2026-09-28T04:09:39.846673488Z"
