apiVersion: v1
entries:
  csi-s3:
  - apiVersion: v1
    appVersion: 0.43.7
    created: "2026-09-28T06:16:50.552850138Z"
    description: Container Storage Interface (CSI) driver for S3 volumes
    digest: 4267b441914dcc254eccea77990f4cd8455e9708e88becb859ff6ff0655ea2d8
    home: https://github.com/yandex-cloud/k8s-csi-s3
    icon: https://raw.githubusercontent.com/yandex-cloud/geesefs/master/doc/geesefs.png
    keywords:
    - s3
    name: csi-s3
    sources:
    - https://github.com/yandex-cloud/k8s-csi-s3/deploy/helm
    urls:
    - https://warjiang.github.io/k8s-csi-s3/charts/csi-s3-0.43.7.tgz
    version: 0.43.7
generated: "2026-09-28T06:16:50.552378675Z"
