name: Release

on:
  push:
    tags:
    - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker
      run: make push REGISTRY_NAME=ghcr.io/${{ github.repository_owner }} VERSION="${GITHUB_REF_NAME#v}"
